syntax = "proto3";
package alg.v1;

message RawImuData {
  uint64 onsensor_timestamp_us = 1;
  uint64 timestamp_ns = 2;
  uint32 type = 3;
  float data_1 = 4;
  float data_2 = 5;
  float data_3 = 6;
  float data_4 = 7;
  float data_5 = 8;
  float data_6 = 9;
}

message BinaryData {
  uint64 onsensor_timestamp_us = 1;
  uint64 timestamp_ns = 2;
  uint32 data_len = 3;
  bytes payload = 4;
}

message ImageData {
  uint64 onsensor_timestamp_us = 1;
  uint64 timestamp_ns = 2;
  string filename = 3; // 原文件名/标识
  bytes image_binary_data = 4;
}

message Ack {
  string note = 1;
}

service AlgService {
  // 一次性发送
  rpc SendRawImuData(RawImuData) returns (Ack);
  rpc SendBinaryData(BinaryData) returns (Ack);
  rpc SendImageDate(ImageData) returns (Ack);
}
